### ISSUE TITLE
Use Unlogged Tables in PostgreSQL

### ISSUE THREAD

**Issue by fabriziomello** [knadh/sql-jobber#13]
Unlogged Tables was first introduced at PostgreSQL 9.1. From [release notes](https://www.postgresql.org/docs/9.1/release-9-1.html#AEN110548):

> * Support unlogged tables using the UNLOGGED option in CREATE TABLE (Robert Haas)
> 
> Such tables provide better update performance than regular tables, but are not crash-safe: their contents are automatically cleared in case of a server crash. Their contents do not propagate to replication slaves, either.

Wonder if can can add this statement here https://github.com/knadh/sql-jobber/blob/master/backends/sqldb.go#L282 ? And perhaps add a new config option  `unlogged = true` that works just for `dbType=postgres`

**Comment by knadh** [comment]
@fabriziomello yep, makes sense for this to be a config option `unlogged = true/false`. To carry this config through, it might make sense to refactor [NewSQLBackend()](https://github.com/knadh/sql-jobber/blob/4944bd64ac20de88d940afd182401965192d37e2/backends/sqldb.go#L56) a `backends.Opt{}` instead of the two individual `dbType, resTable` params, along with the new `unlogged` bool.

Would you be interested in sending a PR for this?

**Comment by fabriziomello** [comment]
@knadh Pushed another version with proposed refactoring
